version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
            - dotnet build -c Release ./Blazor.EventPlanner.csproj
            - dotnet publish -o deployfolder
            
artifacts:
    files:
        - deployfolder/*
    secondary-artifacts:
        artifactIdentifier:
            files: 
                - deployfolder/*
            name:
                BuildTestArtifact
